services:
  # This service bumps the WordPress verion in the Dockerfile to the latest release.
  # See the bin/bump-wordpress.sh script for docs
  #
  # https://hub.docker.com/r/jetbrainsinfra/jq
  bump-wp:
    image: jetbrainsinfra/jq:latest
    volumes:
      - ./:/app
    command: |
      sh /app/bin/bump-wordpress.sh
