version: "3.7"

services:
  wp-cli:
    image: wordpress:cli
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - db
      - wordpress
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/themes/${npm_package_name:-ioptheme}:/var/www/html/wp-content/themes/${npm_package_name:-ioptheme}
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    entrypoint: wp
    command: theme activate ${npm_package_name:-ioptheme}

  composer:
    image: composer:2.0.13
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0-apache
    ports:
      - "8002:80"
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: ~

  webgrind:
    image: creativeprojects/webgrind
    volumes:
      - ./_profiler:/tmp/xdebug

  mysqldump:
    # image: mysql:5.7
    image: mariadb:10.5.9
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src
    environment:
      MYSQL_DATABASE: wordpress

    # NOTE: The mysqldump file will include these CREATE/USE commands:
    #           CREATE DATABASE `wordpress`;
    #           USE `wordpress`;
    #       to drop those lines, remove  "--databases" from the mysqldump command
    command: |
      bash -c 'export DUMPFILE="/usr/src/'${npm_package_name:-dumpfile}'-$$(date +%FT%H%M%S).sql" &&
               echo $${DUMPFILE} &&
               mysqldump -hdb --default-character-set=utf8mb4 --databases $${MYSQL_DATABASE} > "$${DUMPFILE}" &&
               gzip "$${DUMPFILE}" &&
               echo "Successfully dumped MySQL database to \"$${DUMPFILE}.gz\""'

  mysql-reload:
    # image: mysql:5.7
    image: mariadb:10.5.9
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src/dumpfiles
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c 'mysqladmin -hdb -v -f drop $${MYSQL_DATABASE} &&
               mysqladmin -hdb -v -f create $${MYSQL_DATABASE} &&
               echo Database \"$${MYSQL_DATABASE}\" created &&
               echo Reloading database from dumpfile &&
               mysql -hdb $${MYSQL_DATABASE} < $$(ls /usr/src/dumpfiles/*.sql | tail -n1)'

  theme-activate:
    # image: mysql:5.7
    image: mariadb:10.5.9
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src/dumpfiles
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c 'for i in {1..10}; do echo Waiting for MySQL server... && mysql -s -h db -e "exit" && break || sleep 3; done &&
               sleep 2 &&
               echo Connected to MySQL &&
               if [[ $$(mysql -s -h db $${MYSQL_DATABASE} -e "SHOW TABLES LIKE \"wp_options\"") ]]
               then
                 echo Activating theme \"'${npm_package_name:-ioptheme}'\"
                 mysql -h db $${MYSQL_DATABASE} \
                       -e "UPDATE wp_options \
                           SET option_value = \"'${npm_package_name:-ioptheme}'\" \
                           WHERE option_name in (\"template\",\"stylesheet\")"
               else
                 echo Unable to activate theme: 'wp_options' table does not exist.
               fi'

  repair-permissions:
    # image: ideasonpurpose/wordpress:dev
    image: ideasonpurpose/wordpress:0.7.3
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/usr/src/site
    entrypoint: /usr/local/bin/permissions.sh

  pull:
    # image: ideasonpurpose/wordpress:dev
    image: ideasonpurpose/wordpress:0.7.3
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/usr/src/site
    entrypoint: |
      /usr/local/bin/pull.sh
    environment:
      - SSH_KEY_PATH
      - SSH_LOGIN
      - SSH_USER
      - SSH_PORT
      - SSH_WP_CONTENT_DIR
    secrets:
      - SSH_KEY

secrets:
  SSH_KEY:
    file: ${SSH_KEY_PATH:-~/.ssh/your_ssh_private_key}
