services:
  # Primary database for the local WordPress development environment.
  # Image from: https://hub.docker.com/_/mariadb
  db:
    # image: mysql:5.7
    image: mariadb:10.6.5
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d
      # - ./_log/mysql:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Ideas On Purpose's local WordPress development enviornment.
  # Update image version with `docker run ideasonpurpose/wordpress init`
  # Project info: https://github.com/ideasonpurpose/docker-wordpress-dev
  wordpress:
    depends_on:
      - db
    # image: ideasonpurpose/wordpress:dev
    image: ideasonpurpose/wordpress:5.9.2
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/themes/${npm_package_name:-ioptheme}:/var/www/html/wp-content/themes/${npm_package_name:-ioptheme}
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ${DATA_MODEL_PLUGIN:-/tmp/null:/tmp/DATA_MODEL_PLUGIN}
      - ${BLOCKS_PLUGIN:-/tmp/null:/tmp/BLOCKS_PLUGIN}

    environment:
      DATA_MODEL_PLUGIN:
      BLOCKS_PLUGIN:
      WORDPRESS_DEBUG:

        # Apache will throw errors for any ulimit value below 8192
        # NOTE THAT THIS MIGHT BE MORE THAN THE SYSTEM OFFERS
    ulimits:
      nofile: 8192

  # Ideas On Purpose's development toolchain
  # Image from: https://hub.docker.com/r/ideasonpurpose/docker-build
  tools:
    # image: ideasonpurpose/docker-build:dev
    image: ideasonpurpose/docker-build:0.11.0
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - wordpress
    volumes:
      - .:/usr/src/site/
    environment:
      PORT: ${npm_package_config_port:-8080}
    entrypoint: npm run
    command: start

volumes:
  db_data:
    name: ${npm_package_name:-ioptheme}_db
  wp_data:
    name: ${npm_package_name:-ioptheme}_wp
