version: "3.7"

services:
  wp-cli:
    image: wordpress:cli
    user: xfs
    depends_on:
      - db
      - wordpress
    environment:
      WP_CLI_CACHE_DIR: /tmp/wp-cli
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
    entrypoint: wp
    command: theme activate $${NAME:-${npm_package_name:-iopdev}}

  composer:
    image: composer
    volumes:
      - ./:/app
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: ~

  webgrind:
    # user: "33" # www-date on alpine
    image: creativeprojects/webgrind
    volumes:
      - ./_profiler:/tmp/xdebug

  mysqldump:
    image: mysql:5.7
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src
    # NOTE: This mysqldump command includes the lines: 
    #        CREATE DATABASE `wordpress`;
    #        USE `wordpress`;
    # to drop the CREATE/USE database commands remove  "--databases" 
    command: |
      bash -c "export DUMPFILE=$${NAME:-${npm_package_name:-dumpfile}}-$$(date +%FT%H%M%S).sql && \
               mysqldump --default-character-set=utf8mb4 -hdb --databases wordpress > $${DUMPFILE} && \
               tar --remove-files -czf /usr/src/$${DUMPFILE}.zip $${DUMPFILE}"
