version: "3.7"

# Note about devserver-proxy-token--d939bef2a41c4aa154ddb8db903ce19fff338b61
# Since the proxy will be rewriting everytihng and replacing the default hostname,
# we needed a unique value to search for. I couldn't find a way to access a 
# hash ID from the docker-compose file, so we're using this pseudo-unique 
# identifier instead. 

# Docker also appears to normalize hostnames to lowercase, and fails silently when trying to 
# access mixed-case domains. 
#
# TODO: pull something from the environment (somehow?) to make this more unique

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # command: --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    command: > 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci


  wordpress:
    depends_on:
      - db
    image: ideasonpurpose/wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/:/var/www/html/wp-content/
      - ./_log/apache2:/var/log/apache2
      - ./_profiler:/tmp/xdebug_profiler
    # ports:
    #     - "8001:80"
    #   - "127.0.0.3:8008:80"
    ulimits:
        nofile: 8192  # Anything below this and Apache throws an arror
                      # NOTE THAT THIS MIGHT BE MORE THAN THE SYSTEM OFFERS
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

      # APACHE_ULIMIT_MAX_FILES: 1024

      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

      # TODO: This dependency on npm is turning out to be a rather large annoyance
      WORDPRESS_ACTIVE_THEME: ${NAME:-${npm_package_name:-:-iopdev}}

      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        // TODO: Replace those with environment values?, also the networks.default.aliases
        define('WP_HOME', 'http://devserver-proxy-token--d939bef2a41c4aa154ddb8db903ce19fff338b61');
        define('WP_SITEURL', 'http://devserver-proxy-token--d939bef2a41c4aa154ddb8db903ce19fff338b61');
    networks:
      default:
        aliases:
          # Replace this with an environment variable, dotenv? also WORDPRESS_CONFIG_EXTRA
          - devserver-proxy-token--d939bef2a41c4aa154ddb8db903ce19fff338b61

  tools:
    image: ideasonpurpose/docker-build
    user: "1000"  # www-data
    depends_on:
      - wordpress
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    # environment:
      # NAME: ${npm_package_name:-iopdev}
      # VM: devserver-proxy-token--d939bef2a41c4aa154ddb8db903ce19fff338b61
    volumes:
      - ./:/usr/src/site/
    entrypoint: npm run
    command: start

volumes:
  db_data:
  wp_data:
