version: "3.9"

services:
  db:
    # image: mysql:5.7
    image: mariadb:10.5.9
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d
      # - ./_log/mysql:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  wordpress:
    depends_on:
      - db
    image: ideasonpurpose/wordpress:0.7.5
    # image: ideasonpurpose/wordpress:dev
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/themes/${npm_package_name:-ioptheme}:/var/www/html/wp-content/themes/${npm_package_name:-ioptheme}
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ${DATA_MODEL_PLUGIN:-/tmp/null:/tmp/DATA_MODEL_PLUGIN}
      - ${BLOCKS_PLUGIN:-/tmp/null:/tmp/BLOCKS_PLUGIN}

    environment:
      - DATA_MODEL_PLUGIN
      - BLOCKS_PLUGIN

    # Apache will throw errors for any ulimit value below 8192
    # NOTE THAT THIS MIGHT BE MORE THAN THE SYSTEM OFFERS
    ulimits:
      nofile: 8192

  tools:
    image: ideasonpurpose/docker-build:0.9.2
    # image: ideasonpurpose/docker-build:dev
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - wordpress
    volumes:
      - ./:/usr/src/site/
    environment:
      PORT: ${npm_package_config_port:-8080}
    entrypoint: npm run
    command: start

volumes:
  db_data:
    name: ${npm_package_name:-ioptheme}_db
  wp_data:
    name: ${npm_package_name:-ioptheme}_wp
